AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambdaDemo

  Sample SAM Template for sam-java

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  SendFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      DeadLetterQueue:
        Type: SQS
        TargetArn: arn:aws:sqs:ap-northeast-1:471112901071:all-DLQ
      CodeUri: s3://testfloatbucket/app/lambda-demo.zip
      Handler: org.vivalink.handler.SendMsgHandler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        ApiEvent:
          Type:  Api
          Properties:
            Path: /send
            Method: post
  ConsumeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://testfloatbucket/app/lambda-demo.zip
      Handler: org.vivalink.handler.SQSEventsHandler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:ap-northeast-1:471112901071:test-demo
            BatchSize: 10
            Enabled: false
  ConsumeFailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://testfloatbucket/app/lambda-demo.zip
      Handler: org.vivalink.handler.SQSEventsFailHandler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:ap-northeast-1:471112901071:test-demo
            BatchSize: 10
            Enabled: false
  ReProduceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://testfloatbucket/app/lambda-demo.zip
      Handler: org.vivalink.handler.SQSReProduceHandler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:ap-northeast-1:471112901071:test-demo
            BatchSize: 10
            Enabled: false